export const sentence = [
  {
    name: 'index',
    method: 'GET',
    path: '/',
    notShowError: true,
    serverPath: 'https://api.tinker.run/sentence',
  },
  {
    name: 'like',
    method: 'POST',
    path: '/like/:id',
    notShowError: true,
    serverPath: 'https://api.tinker.run/sentence',
  },
  {
    name: 'unlike',
    method: 'POST',
    path: '/unlike/:id',
    notShowError: true,
    serverPath: 'https://api.tinker.run/sentence',
  },
  {
    name: 'collce',
    method: 'POST',
    path: '/collect/:id',
    notShowError: true,
    serverPath: 'https://api.tinker.run/sentence',
  },
  {
    name: 'uncollce',
    method: 'POST',
    path: '/uncollect/:id',
    notShowError: true,
    serverPath: 'https://api.tinker.run/sentence',
  },
  {
    name: 'report',
    method: 'POST',
    path: '/report',
    notShowError: true,
    serverPath: 'https://api.tinker.run/sentence',
  },
  {
    name: 'caihong',
    method: 'GET',
    path: '/',
    notShowError: true,
    serverPath: 'https://api.tinker.run/caihong',
  },
  {
    name: 'caihonglike',
    method: 'POST',
    path: '/like/:id',
    notShowError: true,
    serverPath: 'https://api.tinker.run/caihong',
  },
  {
    name: 'caihongunlike',
    method: 'POST',
    path: '/unlike/:id',
    notShowError: true,
    serverPath: 'https://api.tinker.run/caihong',
  },
  {
    name: 'caihongcollce',
    method: 'POST',
    path: '/collect/:id',
    notShowError: true,
    serverPath: 'https://api.tinker.run/caihong',
  },
  {
    name: 'caihonguncollce',
    method: 'POST',
    path: '/uncollect/:id',
    notShowError: true,
    serverPath: 'https://api.tinker.run/caihong',
  },
  {
    name: 'caihongreport',
    method: 'POST',
    path: '/report',
    notShowError: true,
    serverPath: 'https://api.tinker.run/caihong',
  },
]
